name: Test

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Install Go
  #       uses: actions/setup-go@v2
  #       with:
  #         go-version: 1.17.x
  #     - name: Checkout code
  #       uses: actions/checkout@v2
  #     - name: Run linters
  #       uses: golangci/golangci-lint-action@v2
  #       with:
  #         version: v1.29

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go_version: ["1.15", "1.16", "1.17", "1.18"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go_version }}

      - name: Install dependencies
        run: |
          sudo apt-get update -yqq
          sudo apt-get install pkg-config libgeos-dev -y

      - name: Install go dependencies
        run: go get -t -v ./...

      - name: Run go tests
        run: go test -v -race -cover -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: "v0.1.15"
          files: coverage.txt
          fail_ci_if_error: true
          name: Codecov
          path_to_write_report: coverage.txt
          verbose: true
